/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JTextField;
import project.Guest;
import project.GuestManager;
import project.Room;
import project.RoomManager;
import project.Stay;
import project.StayManager;

/**
 *
 * @author marek
 */
public class CreateStayJDialog extends javax.swing.JDialog {

    private JTableStayModel stayTableModel;
    private JTableRoomModel roomTableModel;
    private JTableGuestModel guestTableModel;
    
    private GuestManager guestManager;
    private RoomManager roomManager;
    private StayManager stayManager;
    
    private boolean stayAlreadyExists;
    //private Guest guest;
    private Stay stay;
            
    /**
     * Creates new form CreateStayJDialog
     */
    public CreateStayJDialog(StayManager stayManager, GuestManager guestManager, RoomManager roomManager, 
            JTableStayModel stayTableModel, JTableRoomModel roomTableModel, JTableGuestModel guestTableModel) {
        stayAlreadyExists = false;
        this.stayManager = stayManager;
        this.roomManager = roomManager;
        this.guestManager = guestManager;
        this.stayTableModel = stayTableModel;
        this.guestTableModel = guestTableModel;
        this.roomTableModel = roomTableModel;
    
        this.stay = new Stay();
        initComponents();
        jTextField1.setVisible(false);
        jLabel3.setVisible(false);
        centerFrame();
    }
    
     public CreateStayJDialog(StayManager stayManager, GuestManager guestManager, RoomManager roomManager, 
            JTableStayModel stayTableModel, JTableRoomModel roomTableModel, JTableGuestModel guestTableModel,
            Stay stay, int guestRow, int roomRow){
        stayAlreadyExists = true;
        this.stayManager = stayManager;
        this.roomManager = roomManager;
        this.guestManager = guestManager;
        this.stayTableModel = stayTableModel;
        this.guestTableModel = guestTableModel;
        this.roomTableModel = roomTableModel;
        this.stay = stay;
        initComponents();
        selectGuestJTable.setRowSelectionInterval(guestRow, guestRow);
        selectRoomJTable.setRowSelectionInterval(roomRow, roomRow);
        Date startDate = stay.getStartOfStay();
        jDateChooserStart.setDate(startDate);
        Date endDate = stay.getEndOfStay();
        jDateChooserEnd.setDate(endDate);
        jTextField1.setText(stay.getPrice().toString());
        centerFrame();
    }
     
    private void centerFrame() {
        Toolkit toolkit = this.getToolkit();
        Dimension screenSize = toolkit.getScreenSize();

        setLocation((screenSize.width / 2) - (this.getWidth() / 2), (screenSize.height / 2) - (this.getHeight() / 2));
    } 
    
    private static final DateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd");
    private Date date(String date) {
        try {
            return DATE_FORMAT.parse(date);
        } catch (ParseException ex) {
            throw new RuntimeException(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        selectGuestJTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        selectRoomJTable = new javax.swing.JTable();
        jDateChooserStart = new com.toedter.calendar.JDateChooser();
        jDateChooserEnd = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("gui/resourcebundles/GUITexts"); // NOI18N
        jLabel1.setText(bundle.getString("createStay.startofstay")); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText(bundle.getString("createStay.endofstay")); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText(bundle.getString("createStay.price")); // NOI18N

        jButton1.setText(bundle.getString("createStay.create")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        selectGuestJTable.setModel(guestTableModel);
        jScrollPane3.setViewportView(selectGuestJTable);

        selectRoomJTable.setModel(roomTableModel);
        jScrollPane4.setViewportView(selectRoomJTable);

        jDateChooserStart.setDateFormatString("yyyy-MM-dd");

        jDateChooserEnd.setDateFormatString("yyyy-MM-dd");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/addStay.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 45, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooserEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooserStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(75, 75, 75))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jDateChooserStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jDateChooserEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int guestRow = selectGuestJTable.getSelectedRow();
        Guest selectedGuest = guestTableModel.getRow(guestRow);
        int roomRow = selectRoomJTable.getSelectedRow();
        Room selectedRoom = roomTableModel.getRow(roomRow);
        JTextField startText = (JTextField)jDateChooserStart.getDateEditor().getUiComponent();
        String startDate = startText.getText();
        JTextField endText = (JTextField)jDateChooserEnd.getDateEditor().getUiComponent();
        String endDate = endText.getText();
        stay.setGuest(selectedGuest);
        stay.setRoom(selectedRoom);
        stay.setStartOfStay(date(startDate));
        stay.setEndOfStay(date(endDate));
        
        if(stayAlreadyExists){
            stay.setPrice(new BigDecimal(jTextField1.getText()));
            stayManager.updateStay(stay);
        }else{ 
            stayManager.createStay(stay);
        }
        stayTableModel.refresh(stayManager.findAllStay());
       
        
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooserEnd;
    private com.toedter.calendar.JDateChooser jDateChooserStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable selectGuestJTable;
    private javax.swing.JTable selectRoomJTable;
    // End of variables declaration//GEN-END:variables
}
