/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import project.Guest;
import project.GuestManager;
import project.Room;
import project.RoomManager;
import project.Stay;
import project.StayManager;

/**
 *
 * @author marek
 */
public class CreateStayJDialog extends javax.swing.JDialog {

    private JTableStayModel stayTableModel;
    private JTableRoomModel roomTableModel;
    private JTableGuestModel guestTableModel;
    private JTableChooseGuestModel chooseGuestTbaleModel;
    
    private GuestManager guestManager;
    private RoomManager roomManager;
    private StayManager stayManager;
    
    private boolean stayAlreadyExists;
    //private Guest guest;
    private Stay stay;
            
    /**
     * Creates new form CreateStayJDialog
     */
    public CreateStayJDialog(StayManager stayManager, GuestManager guestManager, RoomManager roomManager, 
            JTableStayModel stayTableModel, JTableRoomModel roomTableModel, JTableGuestModel guestTableModel,
            JTableChooseGuestModel chooseGuestTbaleModel) {
        stayAlreadyExists = false;
        this.stayManager = stayManager;
        this.roomManager = roomManager;
        this.guestManager = guestManager;
        this.stayTableModel = stayTableModel;
        this.guestTableModel = guestTableModel;
        this.roomTableModel = roomTableModel;
        this.chooseGuestTbaleModel = chooseGuestTbaleModel;
        this.stay = new Stay();
        initComponents();
    }
    
     public CreateStayJDialog(StayManager stayManager, GuestManager guestManager, RoomManager roomManager, 
            JTableStayModel stayTableModel, JTableRoomModel roomTableModel, JTableGuestModel guestTableModel,
            JTableChooseGuestModel chooseGuestTbaleModel, Stay stay){
        stayAlreadyExists = true;
        this.stayManager = stayManager;
        this.roomManager = roomManager;
        this.guestManager = guestManager;
        this.stayTableModel = stayTableModel;
        this.guestTableModel = guestTableModel;
        this.roomTableModel = roomTableModel;
        this.chooseGuestTbaleModel = chooseGuestTbaleModel;
        this.stay = stay;
        initComponents();
        selectGuestJTable.setEditingRow(1);
        selectRoomJTable.setEditingRow(2);
        jFormattedTextField1.setText(stay.getStartOfStay().toString().substring(0, 10));
        jFormattedTextField2.setText(stay.getEndOfStay().toString().substring(0, 10));
        jTextField1.setText(stay.getPrice().toString());
    }
    
    private static final DateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd");
    private Date date(String date) {
        try {
            return DATE_FORMAT.parse(date);
        } catch (ParseException ex) {
            throw new RuntimeException(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        selectGuestJTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        selectRoomJTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("gui/resourcebundles/GUITexts"); // NOI18N
        jLabel1.setText(bundle.getString("createStay.startofstay")); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText(bundle.getString("createStay.endofstay")); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText(bundle.getString("createStay.price")); // NOI18N

        jButton1.setText(bundle.getString("createStay.create")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        selectGuestJTable.setModel(chooseGuestTbaleModel);
        jScrollPane3.setViewportView(selectGuestJTable);

        selectRoomJTable.setModel(roomTableModel);
        jScrollPane4.setViewportView(selectRoomJTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jTextField1))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jFormattedTextField1, jFormattedTextField2, jTextField1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int guestRow = selectGuestJTable.getSelectedRow();
        Guest selectedGuest = guestTableModel.getRow(guestRow);
        int roomRow = selectRoomJTable.getSelectedRow();
        Room selectedRoom = roomTableModel.getRow(roomRow);
        
        stay.setGuest(selectedGuest);
        stay.setRoom(selectedRoom);
        stay.setStartOfStay(date(jFormattedTextField1.getText()));
        stay.setEndOfStay(date(jFormattedTextField2.getText()));
        stay.setPrice(new BigDecimal(jTextField1.getText()));
        
        if(stayAlreadyExists){
            stayManager.updateStay(stay);
        }else{ 
            stayManager.createStay(stay);
        }
        stayTableModel.refresh(stayManager.findAllStay());
       
        
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable selectGuestJTable;
    private javax.swing.JTable selectRoomJTable;
    // End of variables declaration//GEN-END:variables
}
