/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import project.Guest;
import project.HotelManager;
import project.Room;

/**
 *
 * @author marek
 */
public class viewGuestJDialog extends javax.swing.JDialog {

    private JTableGuestModel guestTableModel;
    private JTableRoomModel roomTableModel;
    private HotelManager hotelManager;
    private Guest guest;
    private Room room;
    
    /**
     * Creates new form viewGuestJDialog
     */
    public viewGuestJDialog(HotelManager hotelManager, JTableGuestModel guestTableModel, Room room) {
        this.guestTableModel = guestTableModel;
        this.hotelManager = hotelManager;
        this.room = room;
        initComponents();
        List<Guest> list = new ArrayList<>();
        Guest g = new Guest();
        g =  hotelManager.findCurrentGuestWithRoom(room);
        if(g == null){
            JOptionPane.showMessageDialog(null, "neni zadny aktualni host");
            guestTableModel.refresh(list);
        }else{
            list.add(g);
            guestTableModel.refresh(list);        
            this.setVisible(false);
        }    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(guestTableModel);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
