CREATE TABLE "GUEST"(
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "NAME" VARCHAR(50),
    "SURNAME" VARCHAR(70),
    "ADDRESS" VARCHAR(255),
    "PHONENUMBER" VARCHAR(15)
);

CREATE TABLE "ROOM"(
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "NUMBER" INT NOT NULL,
    "FLOOR" INT NOT NULL,
    "CAPACITY" INT NOT NULL,
    "NOTE" VARCHAR(255),
    "PRICE" INT NOT NULL
);

CREATE TABLE "STAY"(
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "GUEST_ID" BIGINT NOT NULL,
    "ROOM_ID" BIGINT NOT NULL,
    "START_OF_STAY" TIMESTAMP NOT NULL,
    "END_OF_STAY" TIMESTAMP NOT NULL,
    "TOTAL_PRICE" INT NOT NULL 
);